CREATE TABLE [Role] (

	ID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL

)

CREATE TABLE [User](

	ID INT PRIMARY KEY IDENTITY(1,1),
	RoleID INT NOT NULL,
	Username VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Gender VARCHAR(50) NOT NULL,
	[Password] VARCHAR(50) NOT NULL,
	FOREIGN KEY(RoleID) REFERENCES [Role](ID)

)

CREATE TABLE Header(

	ID INT PRIMARY KEY IDENTITY(1,1),
	CustomerID INT NOT NULL,
	StaffID INT NOT NULL,
	[Date] DATE,
	FOREIGN KEY(CustomerID) REFERENCES [User](ID)

)

CREATE TABLE Meat(

	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50)

)

CREATE TABLE Ramen(

	ID INT PRIMARY KEY IDENTITY(1,1),
	MeatID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Broth VARCHAR(50) NOT NULL,
	Price VARCHAR(50) NOT NULL,
	FOREIGN KEY(MeatID) REFERENCES Meat(ID)

)

CREATE TABLE Detail(

	HeaderID INT NOT NULL,
	RamenID INT NOT NULL,
	Quantity INT NOT NULL,
	FOREIGN KEY(HeaderID) REFERENCES Header(ID),
	FOREIGN KEY(RamenID) REFERENCES Ramen(ID),
	PRIMARY KEY(HeaderID, RamenID)
)
